galaxy_info:
  author: Mohamed Ghaleb
  description: "Ansible Azure AD Group management"
  min_ansible_version: 1.9.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system

dependencies: []
