---

- name: eMail | Mail confimration module
  mail:
      host: '{{ SMTP_Server }}'
      port: '{{ SMTP_Port }}'
      username: '{{ SMTP_Username }}'
      password: '{{ SMTP_Password }}'
      charset: 'UTF-8'
      from: '{{ SMTP_From }}'
      to: '{{ SMTP_To }}'
      bcc: '{{ SMTP_BCC }}'
      subject: '{{ send_mail_subject }}'
      body: '{{ send_mail_body }}'
  delegate_to: localhost
  tags: send_mail
