---

- name: Provision the Jumpbox
  hosts: azure-jumphosts
  connection: local
  gather_facts: False
  roles:
    - { role: ansible-azure-provisioner, tags: provision }
    - { role: ansible-pause, tags: pause }

- name: Installing the tools
  hosts: azure-jumphosts
  gather_facts: False
  connection: winrm
  roles:
    - { role: ansible-win-jumphost-packages, tags: installsoftware }
    - { role: ansible-win-thinrdp, tags: thingrdp }
    - { role: ansible-send-mail, tags: sendmail }
